<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="acanthophis" name="TestSuite.ValidationHomePage" tests="8" failures="1" timestamp="2020-05-11T15:11:35 CEST" time="9.139" errors="0">
  <testcase name="testAllCourses" time="0.044" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
  <testcase name="validateNavigationBar" time="0.053" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
  <testcase name="validatePhoneNumber" time="0.067" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
  <testcase name="validateFooter" time="0.049" classname="TestSuite.ValidationHomePage">
    <failure type="java.lang.AssertionError" message="expected [SELF PACED ONLINE TRAINING1] but found [SELF PACED ONLINE TRAINING]">
      <![CDATA[java.lang.AssertionError: expected [SELF PACED ONLINE TRAINING1] but found [SELF PACED ONLINE TRAINING]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestSuite.ValidationHomePage.validateFooter(ValidationHomePage.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateFooter -->
  <system-out/>
  <testcase name="checkNewletters" time="8.767" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
  <testcase name="validateSecondtextOfHeder" time="0.039" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
  <testcase name="validateEmail" time="0.077" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
  <testcase name="validateFirsttextOfHeder" time="0.043" classname="TestSuite.ValidationHomePage"/>
  <system-out/>
</testsuite> <!-- TestSuite.ValidationHomePage -->
